export default {
  "index": "Overview",
  "_template": "API Docs template",
  "account": "Account",
  "admin": "Admin",
  "ping": "Ping",
  "readiness": "Readiness endpoint",
  "usage-bundle": "Usage Bundle",
  "agents": "Agent Pools",
  "agent-tokens": "Agent Tokens",
  "applies": "Applies",
  "assessment-results": "Assessment Results",
  "change-requests": "Change requests",
  "comments": "Comments",
  "configuration-versions": "Configuration Versions",
  "cost-estimates": "Cost Estimates",
  "data-retention-policies": "Data Retention Policies",
  "diagnostics": "Diagnostics",
  "explorer": "Explorer",
  "github-app-installations": "GitHub App Installations",
  "cidr-range-lists": "IP allowlist",
  "nodes": "Nodes",
  "notification-configurations": "Notification Configurations",
  "no-code-provisioning": "No-Code Provisioning",
  "oauth-clients": "OAuth Clients",
  "oauth-tokens": "OAuth Tokens",
  "organizations": "Organizations",
  "organization-memberships": "Organization Memberships",
  "organization-tags": "Organization Tags",
  "organization-tokens": "Organization Tokens",
  "plan-exports": "Plan Exports",
  "plans": "Plans",
  "policies": "Policies",
  "policy-checks": "Policy Checks",
  "policy-evaluations": "Policy Evaluations",
  "policy-sets": "Policy Sets",
  "policy-set-params": "Policy Set Parameters",
  "private-registry": "Private Registry",
  "projects": "Projects",
  "project-team-access": "Project Team Access",
  "reserved-tag-keys": "Reserved Tag Keys",
  "run": "Runs",
  "run-tasks": "Run Tasks",
  "run-triggers": "Run Triggers",
  "scim": "SCIM",
  "ssh-keys": "SSH Keys",
  "stacks": "Stacks",
  "state-versions": "State Versions",
  "state-version-outputs": "State Version Outputs",
  "support-bundle": "Support Bundles",
  "team-access": "Team Access",
  "team-members": "Team Membership",
  "team-tokens": "Team Tokens",
  "teams": "Teams",
  "user-tokens": "User Tokens",
  "users": "Users",
  "variables": "Variables",
  "vcs-events": "VCS Events",
  "workspaces": "Workspaces",
  "workspace-variables": "Workspace-Specific Variables",
  "workspace-resources": "Workspace Resources",
  "workspace-transfers": "Workspace Transfers",
  "variable-sets": "Variable Sets",
  "changelog": "Changelog",
  "stability-policy": "Stability Policy",
  "queries": "Queries"
}
