export default {
  "index": "Overview",
  "_template": "API docs template",
  "account": "Account",
  "agents": "Agent pools",
  "agent-tokens": "Agent tokens",
  "applies": "Applies",
  "audit-trails": "Audit trails",
  "audit-trails-tokens": "Audit trails tokens",
  "assessment-results": "Assessment results",
  "change-requests": "Change requests",
  "comments": "Comments",
  "configuration-versions": "Configuration versions",
  "cost-estimates": "Cost estimates",
  "explorer": "Explorer",
  "feature-sets": "Feature sets",
  "github-app-installations": "GitHub app installations",
  "hold-your-own-key": "Hold your own key",
  "invoices": "Invoices",
  "cidr-range-lists": "IP allowlists",
  "ip-ranges": "IP ranges",
  "metrics-service-tokens": "Metrics service tokens",
  "no-code-provisioning": "No-code provisioning",
  "notification-configurations": "Notification configurations",
  "oauth-clients": "OAuth clients",
  "oauth-tokens": "OAuth tokens",
  "organizations": "Organizations",
  "organization-memberships": "Organization memberships",
  "organization-tags": "Organization tags",
  "organization-tokens": "Organization tokens",
  "plan-exports": "Plan exports",
  "plans": "Plans",
  "policies": "Policies",
  "policy-checks": "Policy checks",
  "policy-evaluations": "Policy evaluations",
  "policy-sets": "Policy sets",
  "policy-set-params": "Policy set parameters",
  "private-registry": "Private registry",
  "projects": "Projects",
  "project-team-access": "Project team access",
  "queries": "Queries",
  "reserved-tag-keys": "Reserved tag keys",
  "run": "Runs",
  "run-triggers": "Run triggers",
  "ssh-keys": "SSH keys",
  "state-versions": "State versions",
  "state-version-outputs": "State version outputs",
  "subscriptions": "Subscriptions",
  "stacks": "Stacks",
  "tasks": "Tasks",
  "team-members": "Team membership",
  "group-member-roles": "Group member roles",
  "team-tokens": "Team tokens",
  "teams": "Teams",
  "terraform-actions": "Terraform actions",
  "user-tokens": "User tokens",
  "users": "Users",
  "variables": "Variables",
  "variable-sets": "Variable sets",
  "vcs-events": "VCS events",
  "workspaces": "Workspaces",
  "workspace-variables": "Workspace-specific variables",
  "team-access": "Workspace team access",
  "workspace-resources": "Workspace resources",
  "changelog": "Changelog",
  "stability-policy": "Stability policy"
}
